### ISSUE TITLE
189错误

### ISSUE THREAD

**Issue by dizicheng** [Magisk-Modules-Repo-CN/magisk_modules_backuper#1]
所有的都是
rm: ./modbaks/disabled: No such file or directory
/system/bin/magiskmodbak[189]: zip: not found
  xposed 备份失败

给了root

**Comment by cjybyjk** [comment]
首先确保你在使用Neoterm 或者 termux 等终端
然后执行 apt install zip

这是我的疏忽，忘了在说明里加上...

**Comment by Flyfish233** [comment]
这样的做法是无效的。按照上面的方法照样提示Not Found。尝试在 Termux 上安装 tsudo 以在有 Root 权限的同时调用 zip。

**Comment by cjybyjk** [comment]
@Flyfish233 等下会更新使用p7zip的版本

**Comment by kmvan** [comment]
直接gz就好啦。
